name: Deploy Shiny app
on:
  push:
    branches: [main]
    paths:
      - '*.parquet'
      - '*.r'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/shiny:4.4.1
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: install2.r arrow hrbrthemes patchwork rsconnect tidyverse tsibble zoo

      - name: Deploy Shiny app
        run: Rscript deploy.r
        env:
          SHINY_ACCOUNT_NAME: ${{ secrets.SHINY_ACCOUNT_NAME }}
          SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
